import sys
sys.path.append('../../modules')
import torch
import EBA as eba
import similarity_matrix as sm
import embedding as emb

### load language model extractor: ProtT5 or ESMb1
print('Loading ProtT5 model...')
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
protT5_ext = emb.load_extractor('ProtT5', 'residue', device=device)
print('Model loaded.')

LECA_DIOGU = 'ADTIVAVELDSYPNTDIGDPSYPHIGIDIKSIRSKSTARWNMQTGKVGTAHISYNSVAKRLSAVVSYTGSSSTTVSYDVDLNNVLPEWVRVGLSATTGLYKETNTILSWSFTSKLKTNSIADANSLHFSFNQFSQNPKDLILQSDATTDSDGNLELTKVSSSGDPQGSSVGRALFYAPVHIWEKSAVVAGFDATFTFLIKSPDRDPADGITFFIANTDTSIPSGSGGRLLGLFPDAN'
AAD48977 = 'MKALLFLLTLFLILPNPISAIDFIFNGFNDSSSNVSLFGIATIESKILTLTNQTSFATGRALYNRTIRTKDPITSSVLPFSTSFIFTMAPYKNTLPGHGIVFLFAPSTGINGSSSAQHLGLFNLTNNGNPSNHIFGVEFDVFANQEFSDIDANHVGIDVNSLHSVYSNTSGYWSDDGVVFKPLKLNDGRNYQVWIDYRDFVVNVTMQVAGKIRPKIPLLSTSLNLSDVVEDEMFVGFTAATGRLVQSHKILAWSFSNSNFSLSNSLITTGLPSFVLPKDSIVKAKWFVFVLVLICFLVVALVGLVLFAVVRKRLERARKRALMEDWEMEYWPHRIPYEEIESGTKGFDEKNVIGIGGNGKVYKGLLQGGVVEVAVKRISQESSDGMREFVAEISSLGRLKHRNLVSLRGWCKKEVGSFMLVYDYMENGSLDRWIFENDEKITTLSCEERIRILKGVASGILYLHEGWESKVLHRDIKASNVLLDRDMIPRLSDFGLARVHGHEQPVRTTRVVGTAGYLAPEVVKTGRASTQTDVFAYGILVLEVMCGRRPIEEGKKPLMDWVWGLMERGEILNGLDPQMMMTQGVTEVIDEAERVLQLGLLCAHPDPAKRPSMRQVVQVFEGDKAEIFEAESSEDVESWMLMKMGSRGSSREFWYGSSSHPTIEQIRLQSLSVSLSSWNSSILEGR'

### extract per-residue embeddings
emb1 = protT5_ext.extract(LECA_DIOGU)
emb2 = protT5_ext.extract(AAD48977)

### compute similarity matrix and "re-scale" it by subtracting a constant
K = 2
similarity_matrix = sm.compute_similarity_matrix(emb1, emb2)-K
eba_results = eba.EBA_local(similarity_matrix, gap_penalty=2)

### print the resulting local alignments
for idx,alg in enumerate(eba_results):
    print('alignment score {}'.format(alg[2]/alg[0].shape[0]))
    print('limits: LECA_DIOGU: {}-{}, AAD48977 {}-{}'.format(alg[0][0],alg[0][-1],alg[1][0],alg[1][-1]))